// src/utils/imageClickLogic.js

// Define stories corresponding to each correct order
const stories = {
	'goose,panda,basketball,singapore': "Chonk befriends Twinkle Panda in outer space. 'Howdy mate, would you like to play basketball?' 'Yes, I'd love to!' answers Twinkle Panda. Chonk destroys Twinkle Panda in a 10-1. 'Aww man, I lost the bet,' says Twinkle Panda. 'Would you like to come visit my hometown?' 'Sure, beats staying in outer space my whole life!' says Chonk. They both head to Singapore and continue their basketball adventures.",
	'goose,panda,singapore,basketball': "Chonk befriends Twinkle Panda in Singapore. 'Yo, what's up bro' says Chonk. 'Hey bro, what's up?' replies Twinkle Panda. 'The weather is absolute dog crap but despite that, it's the perfect place for not just you to live but also me. 'Oh, how come?' asks Twinkle Panda. People around Marina Bay Sands look at them two as if they're crazy. 'Look at that twinkly water. Plus you've got Kai Kai and Jia Jia.' 'You're right. Nothing beats home.' says Twinkle Panda.",
	'goose,singapore,panda,basketball': "Chonk takes a flight to Singapore to study abroad. He meets Twinkle Panda at National University of Singapore. They introduce themselves and have a nice conversation. 'So what's your major?' asks Chonk. 'I'm studying why my species isn't extinct yet. What about you?' 'Oh, I'm studying ways to invent teleportation, time travel, and cloning.' says Chonk. 'Oh interesting, what for?' asks Twinkle Panda. 'World domination!' exclaims Chonk. 'Oh.... ummmm okay.' says Twinkle Panda. 'Hey, wanna go play basketball?' asks Chonk. 'Sure, loser lose 10 bucks.' 'It's on', exclaims Chonk as his eyes widened with determination.",
	'goose,singapore,basketball,panda': "Chonk visits Singapore with a purpose of playing basketball with Luka. 'Yo Luka, what up what brings you here?' says Chonk as he gives Luka a bro hand shake and chest bump. 'Ah nothing much, just basketball competition. What about you?' 'Obviously to watch you compete!' 'Nice,' says Luka '... and attack you and make you a basketball goose.' 'What'd you say?' asked Luka. 'Nothin', said Chonk. During basketball game, Chonk met a panda. 'Hello, what's your name?' 'My name is Twinkle', said the panda. Chonk dies laughing at the name and embarasses himself in front of the entire crowd.",
	'goose,basketball,singapore,panda': "Chonk is playing basketball in Austin with the goose gang. 'Hey, would you guys like to visit Singapore?' asks Chonk. 'HONK!', replies everyone. The flock flies to the lion city that is Singapore and they quickly locate the basketbal courts. They scare and chase all the humans away as they pridefully stride into the gymnasium to see a group of pandas playing half court. 'Yo, wanna play a game?' asks Chonk. The most twinkly panda out of the all responds with 'You bet'. Little did the pandas know that that geese would beat them 9-1.",
	'goose,basketball,panda,singapore': "Chonk is playing basketball himself and wonders 'Man, wouldn't it be so much better if I was playing in a group?' He finds another animal around, who turns out to be a very twinkly panda. 'YO would you like to play basketball?' 'I don't know how to play basketball' the panda says. 'It's ok, I can teach you. I've been wanting to teach someone' The twinkly panda agrees. 'Oh wait but first, let's go to Singapore. I've always wanted to visit.' Chonk drags twinkly panda to Singapore to play basketball. 'Wow, basketball is very tough', says the twinkly panda. 'My goal is to make at least 15 shots today.' 'You got this', said Chonk who sees full potential in the twinkly panda at the NBA.",
	
	'panda,goose,basketball,singapore': "Twinkle Panda befriends a goose. 'Hello there, what's your name?' 'I'm Chonk! What's your name?' 'Hmmm, I feel like I've seen you somewhere before... are you that video game character?' asks Twinkle Panda. 'Well, I geuss I just have one of those faces' said Chonk as he heaves a sigh. 'Do you wanna play basketball?' asks Twinkle Panda. 'HONK!' honks Chonk. Twinkle Panda tries to kidnap Chonk because he wasn't listening to Twinkle Panda, so she took more extreme measures. Chonk woke up in a storage unit in Singapore with a basketball court. He happily obliged and beat Twinkle Panda in a game 10-0.",
	'panda,goose,singapore,basketball': "Twinkle Panda meets a silly goose in the neighborhood bothering humans. The panda witnesses the goose chasing people, stealing their slipper, and messing with their belongings. As a citizen of Singapore, Twinkle Panda reports the silly goose to the authority, earning the goose a 1-month ticket to jail. The silly goose fought his way against the police, but eventually gets taken by the police to prison. He messes with his inmates and destroys everyone at basketball, earning himself the nickname of the Slam Honk.",
	'panda,basketball,goose,singapore': "Twinkle Panda is playing basketball with her panda friends. A goose comes along and invites her to do a special dance at his wedding. 'Why would you like to invite me to your wedding?' 'Are you kidding me?' asked the goose, 'You're the one and only Twinkle Panda. I've seen your dances all over social media. I know it's you.' Twinkle Panda and the goose strikes a deal. They both fly out to Singapore, where the wedding is held. Twinkle Panda delivers a beautiful performance, blinding all the geese with her charm.",
	'panda,basketball,singapore,goose': "Twinkle Panda was playing basketball in Austin. 'Hmmm, I wonder how much more fun I'd have if I was playing basketball in Singapore. She invents teleportation and pops up in Singapore. She blinds everyone in her path until she bumps into a goose. 'Hey there, what's your name?' asked Twinkle Panda. 'My naem is silly goose.' Twinkle Panda laughed at his name, which the silly goose found offensive. He attacks Twinkle Panda, but she rejects it. 'Would you like to play basketball?' asks Twinkle Panda. 'HONK!' goes silly goose. They find all the courts taken, so they each took turns being the basketball hoop for each other.",
	'panda,singapore,basketball,goose': "Twinkle Panda lives in China and was given to Singapore as a gift. She was known as the Hoop Bear, so the zoo gave her a basketball hoop for her to play. This attracted a lot of visitors as a result. One day, a goose was visiting the zoo and spots the Hoop Bear. The goose immediately laser focuses his eyes on the hoop and breaks through the glass. All the humans are shocked to see the goose join Hoop bear to play basketball. To this day, they earn the title of Splash Gonda.",
	'panda,singapore,goose,basketball': "Twinkle Panda lives in the Singapore zoo. One night, she decided to break out of the zoo. Along the way, she met a goose who wanted to escape with her. As they tip toe around the zoo, Twinkle Panda whispers 'So why would you like to break out of the zoo?' 'I am basketball deprived.' said the goose. 'Would you like to go play basketball them?' asks Twinkle Panda. 'Is that even a question?' said the goose as he looked her in the eyes. They run off to an outdoor basketball court and play a game of basketball, which is a vibe neither of them have felt before.",

	'basketball,goose,panda,singapore': "A group of snappy geese were playing basketball. Honk, being the brave goose he is, waddles up to them. He gets chased away by the other geese. 'Welp, that just happened,' he thought to himself. A panda approaches him and goes 'Hey, would you like to join us?' Honk looks around but doesn't see any courts but enthusiastically replies with, 'Sure, I'd love to!'. There was an awkward moment of silence before a very intense staring competition. As Honk was focused zoned in, the panda kidnaps Honk and teleports them to Singapore to join the BAS.",
	'basketball,goose,singapore,panda': "Honk gets drafted into the NBA as part of the Dallas Mavericks. He is a huge fan of Luka and they have a conversation about his best friend Twinkle Panda. 'There's someone out there named Twinkle Panda?' asked Luka in shock. He bursts out laughing and laughed until he couldn't even breathe. 'Wow, that's rude', says Honk. 'Anyways, you guys should meet. I wanna introduce you two and see how it goes.' 'Oh hell no,' says Luka. 'I think you'd be interested. He is playing for the BAS.' said Honk. 'Oh really? That's sick. Sure I'm down' says Luka. Honk and Luka fly over to Singapore to meet Twinkle Panda.",
	'basketball,singapore,goose,panda': "The BAS is recruiting new players for the team. A lot of people audition, but a goose and a panda decide to team up and chase all the humans away. 'We are better when we are together!!!! LEEEESSSS HOOOOOOONNNKKKKKKKK!!!!' they yell to hype themselves up. They end up playing several 1-1 rounds with each other. The game resulted in a tie. The BAS makes an executive decision to take in a goose and a panda to their team. The BAS begins dominating international competitions and winning several awards, achieving worldwide recognition. Being in the spotlight, they found joy and continued bonding through fond memories.",
	'basketball,singapore,panda,goose': "A basketball was awoken by a lightning strike in Singapore. It begins hopping around, trying to find its owner. It was a rainy night. The basketball hops into a third-story shophouse, where a panda was asleep. It jumps on the panda, scaring the living daylights out of it. 'AHHHH what was that?' goes the panda. He notices a moving basketball in front of him. 'I must be dreaming,' he goes. The basketball hits him in the face, telling him this is not a dream. 'Well, I do enjoy basketball. Do you wanna go for a couple rounds?' The basketball nods. The panda calls up his friend the goose and they break into NUS to play basketball. They ended up getting arrested and taken away by the human police, along with the basketball.",
	'basketball,panda,singapore,goose': "A basketball with eyes rolls up to a panda in the zoo. 'Hey there, whatchu doing there, lil fella?' asks the basketball. 'Omg you can talk!' says the panda. 'This is a sign I should go play basketball!' The panda finds a basketball court in the Singapore zoo. Seeing a panda and a basketball walk around proudly, a goose approaches them and honks 'Can I join?' '그럼요!' They go play basketball together and they make the news. Before they knew it, they became famous celebrities. The BAS decided to seek them out and their life has been changed for the better ever since.",
	'basketball,panda,goose,singapore': "A deflated basketball was found on the Gardens basketball court at A&M. A panda walks up to the court and goes, 'welp, that's dead. Who's is this?' The panda decides to kick it aside and start shooting hoops. Later, a silly goose waddles up to the court. 'Ah there it is! I've been searching all over for you!' honked the goose as he rushes to retrieve his basketball. The panda looks at the goose and says 'Is that your ball? I know where there are golden basketballs, would you like one?' 'HONK' says the goose. They both travel to Singapore, which is home to the most golden basketball in the world. They steal the nation's treasure and returns to the Gardens to play with their newfound basketball.",

	'singapore,goose,panda,basketball': "Before Singapore was founded, it was believed to be inhabited by the geese kingdom. One day, the pandas sail from Twinkle Pinky land to Singapore, claiming that this little island will be theirs from now on. The snappy geese and twinkle pinky pandas wouldn't go down without a fight, so they played a game of basketball. The snappy geese beat the twinkle pinky pandas 9-1. The geese kingdom continues to reign in Singapore happily ever after.",
	'singapore,goose,basketball,panda': "A group of geese decided to study abroad in Singapore. They visited the merlion and for some strange reason, saw a basketball with a mind of its own bouncing around. The basketball bonked all the geese in the head so of course the geese couldn't go down without a battle. They chased the basketball while violently honking at humans to get out of their way. They follow the basketball to the Singapore zoo, where a group of pandas were. They soon realized they were the chosen one to be summoned, and decided to ditch their study abroad to play basketball with the pandas.",
	'singapore,panda,goose,basketball': "Kai Kai and Jia Jia were pandas gifted to Singapore in 2012 and were returning in 2024. Both pandas didn't want to leave, so they plotted to have some smart geese help them sneak out. As nighttime before their departure date came, the geese successfully helped Kai Kai and Jia Jia escape. After they got past the guards and out of the zoo, they decided to fly to the Americas to play basketball for eternity.",
	'singapore,panda,basketball,goose': "In Singapore, Twinkle Panda was wandering around Marina Bay Sands, looking for a way to entertain herself. She stumbled upon a public basketball court and decided to give the sport a try. As she dribbled the basketball, she noticed a group of geese watching her intently from the sidelines. Intrigued, a geese named Chonk waddled over to join the game. Twinkle Panda and the geese quickly formed a unique team. The crowds of spectators couldn't believe their eyes as the panda and geese played together seamlessly, eventually becoming a beloved spectacle in Singapore's basketball scene.",
	'singapore,basketball,goose,panda': "In Singapore, a BAS game was going on. Chonk waddles past security without pass and goes to the stadium and steals a random seat. Once the game started, a Twinkle Panda followed Chonk's footsteps and sat next to him. 'So interesting game, huh?' asks Twinkle Panda. 'Yeah', replies Chonk. 'Wouldn't it be better if we took over the game?' said Twinkle Panda with an evil grin. Chonk side-eyes Twinkle Panda. Their thoughts unite and they jump from the bleachers onto the basketball court and starts playing basketball. The crowd was appalled, but soon realized that the goose and panda were pretty good at what they do. Everyone started cheering them on, and they quickly captured the hearts of Singapore.",
	'singapore,basketball,panda,goose': "A flying basketball that can travel at the speed of light was zooming around in outer space and decides to land in Singapore. It chose to land directly on a panda, who was doing a handstand wagging its butt in the air like they just don't care. The panda, startled, introduces itself as Twinkle Panda. It pounces at the basketball, which zoomed in the other direction, crashed through the display glass, and into River Wonders where a flock of geese are. The geese start honking at the basketball and chasing after it, as the basketball also realizes all the pandas, not just Twinkle Panda, are coming after it. The basketball decides to escape with its life, just inches away from being chewed like a toy.",

	// Add more stories as needed
  };
  
  // Default story for incorrect orders
  const wrongOrderStory = "Oops! You clicked the images in the wrong order. Try again!";
  
  export { stories, wrongOrderStory };
  